export const APP_CONFIG = {
    MAX_RECENT_TRANSACTIONS: 5,
    MAX_ACCOUNTS_PER_USER: 5,
    TRANSACTIONS_PER_PAGE: 20,
    DEFAULT_CURRENCY: "GBP",
    DEFAULT_CURRENCY_SYMBOL: "£",
    DATE_RANGE_DEFAULT_MONTHS: 1,
} as const;
